#!/usr/bin/env bash

echo "======= backing up your notebook before you proceed =========="
#read

cp Assignment.ipynb Assignment.backup.ipynb
echo "======= commiting your changes =========="
git commit -am "My progress so far."
echo "======= pull updates =========="
git pull --no-edit upstream main -X ours
